name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test

      - name: Upload reports
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: Test reports
          path: build/reports
          if-no-files-found: warn

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew lint

      - name: Upload reports
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: Lint reports
          path: build/reports
          if-no-files-found: warn
